### ISSUE TITLE
Should Identical rows be pulled out of the results table?

### ISSUE THREAD

**Issue by KnockerPulsar** [EssamWisam/MLPath#1]
For example, let's say I have several runs with one parameter being the same for all of them, wouldn't it be better to pull that out instead of taking precious horizontal space?

My suggestion would be to have a vertical table for all of these parameters such that the output is like this:
|run| param1 | prarm 2|
|----|------------|-----------|
|... | ..............| ............|
|... | ..............| ............|

Parameters shared between all runs:
|param name| param value |
|----|------------|
|... | ..............|
|... | ..............|

**Comment by EssamWisam** [comment]
Sorry if I did not respond on time. I think around the time of your issue I mad it such that duplicate rows are eliminated and only changed columns are highlighted in the csv. Maybe pip install the newest version. Note as well that you can always configure the columns to view from the json config file.
